### ISSUE TITLE
limit the size of files in the directory /var/lib/docker/volumes/optimism_data,

### ISSUE THREAD

**Issue by ting9114** [a16z/magi#168]
How can I limit the size of files in the directory /var/lib/docker/volumes/optimism_data, as these data occupy more than 700 GB, and I am currently unsure if I can delete the data? The files taking up the most space in this directory are located at /var/lib/docker/volumes/optimism_data/_data/geth/geth/chaindata/ancient#.

**Comment by borispovod** [comment]
When you initialize the environment using Docker, it downloads the current snapshots for the choosen network. It seems you might have used the Optimism mainnet, given its size of 700 GB. To clear that data, you can delete the Docker volumes. You also have the option to reduce the Docker virtual disk size. However, doing so might cause it to stop downloading the snapshot data and exit due to insufficient space

**Comment by ncitron** [comment]
Yep Optimism mainnet is quite large. Unfortunately not much we can do to change that.
